import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "./components/context/AuthUserContext";
import { ToastProvider } from "./components/context/ToastContext";
import ActiveCompanyProvider from "./components/context/ActiveCompanyContext";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${poppins.variable} antialiased`}
    >
      <body className="font-body relative">
        <ToastProvider>
          <AuthUserProvider>
            <ActiveCompanyProvider>
              {children}
            </ActiveCompanyProvider>
          </AuthUserProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
