import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "./components/context/AuthUserContext";
import { ToastProvider } from "./components/context/ToastContext";
import ActiveCompanyProvider from "./components/context/ActiveCompanyContext";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${manrope.variable} ${inter.variable} antialiased`}
    >
      <body className="font-body relative">
        <ToastProvider>
          <AuthUserProvider>
            <ActiveCompanyProvider>
              {children}
            </ActiveCompanyProvider>
          </AuthUserProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
