CREATE TYPE "CompanyLegalStatus" AS ENUM (
  'MICRO_ENTERPRISE', 'INDIVIDUAL_ENTREPRENEUR', 'EIRL', 'EURL', 'SARL',
  'SELARL', 'SASU', 'SAS', 'SELAS', 'SA', 'SELAFA', 'SCA', 'SELCA', 'SNC',
  'SCS', 'SLP', 'SOCIETE_CIVILE', 'SCI', 'SCM', 'SCP', 'EARL', 'GAEC',
  'SCEA', 'GIE', 'ASSOCIATION', 'FONDATION', 'MUTUELLE', 'COOPERATIVE',
  'ETABLISSEMENT_PUBLIC', 'COLLECTIVITE_TERRITORIALE', 'SOCIETE_ETRANGERE',
  'OTHER'
);

ALTER TABLE "Company"
  ADD COLUMN "legalStatus" "CompanyLegalStatus" NOT NULL DEFAULT 'MICRO_ENTERPRISE';

UPDATE "Company"
SET "vatRegime" = 'VAT_EXEMPTION'
WHERE "vatRegime" IS NULL;

ALTER TABLE "Company"
  ALTER COLUMN "vatRegime" SET DEFAULT 'VAT_EXEMPTION',
  ALTER COLUMN "vatRegime" SET NOT NULL,
  ALTER COLUMN "isVatExempt" SET DEFAULT true;
