import { apiServer } from '@/lib/api-server';

type Dashboard = { users: number; owners: number; employees: number; activeCompanies: number; failedPayments: number; subscriptions: Array<{ subscriptionPlan: string; _count: number }>; recentUsers: Array<{ id: string; firstname: string; lastname: string; email: string }> };
export default async function AdminPage() {
  const response = await apiServer<Dashboard>('api/admin/dashboard');
  if (!response.ok) return <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">Accès administrateur requis.</p>;
  const metrics = [['Utilisateurs', response.data.users], ['Propriétaires', response.data.owners], ['Employés', response.data.employees], ['Entreprises actives', response.data.activeCompanies], ['Paiements en échec', response.data.failedPayments]];
  return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 font-title text-3xl font-semibold text-zinc-900">{value}</p></article>)}</section><section className="rounded-2xl border border-zinc-200 bg-white p-5"><h2 className="font-title text-lg font-semibold">Abonnements</h2><div className="mt-4 flex flex-wrap gap-3">{response.data.subscriptions.map((item) => <span key={item.subscriptionPlan} className="rounded-lg bg-primary/10 px-3 py-2 text-sm font-semibold text-primary">{item.subscriptionPlan} · {item._count}</span>)}</div></section><section className="rounded-2xl border border-zinc-200 bg-white p-5"><h2 className="font-title text-lg font-semibold">Inscriptions récentes</h2><ul className="mt-3 divide-y divide-zinc-100">{response.data.recentUsers.map((user) => <li key={user.id} className="py-3 text-sm"><strong>{user.firstname} {user.lastname}</strong><span className="ml-2 text-zinc-500">{user.email}</span></li>)}</ul></section></div>;
}
