'use client';
import { Bell, Download, FileInput, Inbox } from 'lucide-react';
import { useEffect, useState } from 'react';
import { getMyCompanies } from '@/lib/companies/companies';
import { AppNotification, downloadSupplierInvoice, getNotifications, getSupplierInvoices, markNotificationRead, SupplierInvoice, synchronizeSupplierInvoices } from '@/lib/notifications/notifications';
import { useToast } from '@/app/components/context/ToastContext';

export default function NotificationsPage() {
  const [view, setView] = useState<'notifications' | 'supplier-invoices'>('notifications');
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [invoices, setInvoices] = useState<SupplierInvoice[]>([]);
  const [companyId, setCompanyId] = useState<string | null>(null);
  const [isSynchronizing, setIsSynchronizing] = useState(false);
  const [downloadingInvoiceId, setDownloadingInvoiceId] = useState<string | null>(null);
  const { showToast } = useToast();
  useEffect(() => { if (new URLSearchParams(window.location.search).get('view') === 'supplier-invoices') setView('supplier-invoices'); }, []);
  useEffect(() => { void getNotifications().then((r) => r.ok && setNotifications(r.data)); }, []);
  async function loadInvoices(id: string) { const response = await getSupplierInvoices(id); if (response.ok) setInvoices(response.data); }
  useEffect(() => { void getMyCompanies().then((r) => { const id = r.ok ? r.data.activeCompanyId : null; setCompanyId(id); if (id) void loadInvoices(id); }); }, []);
  async function synchronize() { if (!companyId) return; setIsSynchronizing(true); const response = await synchronizeSupplierInvoices(companyId); setIsSynchronizing(false); if (response.ok) await loadInvoices(companyId); }
  async function download(invoice: SupplierInvoice) { if (!companyId) return; setDownloadingInvoiceId(invoice.id); const response = await downloadSupplierInvoice(companyId, invoice.id); setDownloadingInvoiceId(null); if (!response.ok) { showToast(typeof response.error.message === 'string' ? response.error.message : 'Impossible de télécharger la facture.', 'error'); return; } showToast('Facture téléchargée.', 'success'); }
  async function open(notification: AppNotification) { if (!notification.readAt) { await markNotificationRead(notification.id); setNotifications((all) => all.map((item) => item.id === notification.id ? { ...item, readAt: new Date().toISOString() } : item)); } if (notification.href) window.location.assign(notification.href); }
  return <main className="mx-auto w-full max-w-5xl p-5 sm:p-8"><h1 className="font-title text-2xl font-semibold text-zinc-900">Centre de notifications</h1><p className="mt-1 text-sm text-zinc-500">Suivez votre activité et vos factures fournisseurs.</p>
    <div className="mt-6 flex gap-2 border-b border-zinc-200"><button onClick={() => setView('notifications')} className={`flex items-center gap-2 px-4 py-3 text-sm font-medium ${view === 'notifications' ? 'border-b-2 border-primary text-primary' : 'text-zinc-500'}`}><Bell className="h-4 w-4" />Notifications</button><button onClick={() => setView('supplier-invoices')} className={`flex items-center gap-2 px-4 py-3 text-sm font-medium ${view === 'supplier-invoices' ? 'border-b-2 border-primary text-primary' : 'text-zinc-500'}`}><FileInput className="h-4 w-4" />Factures fournisseurs</button></div>
    {view === 'notifications' ? <div className="mt-5 space-y-3">{notifications.map((n) => <button key={n.id} onClick={() => void open(n)} className={`w-full rounded-xl border p-4 text-left ${n.readAt ? 'border-zinc-200 bg-white' : 'border-primary/30 bg-primary/5'}`}><p className="font-semibold text-zinc-900">{n.title}</p><p className="mt-1 text-sm text-zinc-600">{n.message}</p><p className="mt-2 text-xs text-zinc-400">{new Date(n.createdAt).toLocaleString('fr-FR')}</p></button>)}{!notifications.length && <Empty icon={<Bell />} text="Aucune notification pour le moment." />}</div> : <div className="mt-5 overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="flex justify-end border-b border-zinc-200 p-3"><button onClick={() => void synchronize()} disabled={!companyId || isSynchronizing} className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{isSynchronizing ? 'Import…' : 'Importer depuis SuperPDP'}</button></div><table className="w-full text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="p-3">Fournisseur</th><th className="p-3">Facture</th><th className="p-3">Émise le</th><th className="p-3 text-right">Total TTC</th><th className="p-3"><span className="sr-only">Télécharger</span></th></tr></thead><tbody>{invoices.map((i) => <tr key={i.id} className="border-t border-zinc-100"><td className="p-3 font-medium">{i.supplierName ?? 'Fournisseur inconnu'}</td><td className="p-3">{i.invoiceNumber ?? '—'}</td><td className="p-3">{i.issuedAt ? new Date(i.issuedAt).toLocaleDateString('fr-FR') : '—'}</td><td className="p-3 text-right">{Number(i.totalIncludingTax).toFixed(2)} {i.currencyCode}</td><td className="p-3 text-right"><button type="button" onClick={() => void download(i)} disabled={downloadingInvoiceId === i.id} className="inline-flex items-center gap-2 rounded-md px-3 py-2 font-semibold text-primary hover:bg-primary/10 disabled:cursor-not-allowed disabled:opacity-60"><Download className="h-4 w-4" />{downloadingInvoiceId === i.id ? 'Téléchargement…' : 'Télécharger'}</button></td></tr>)}</tbody></table>{!invoices.length && <Empty icon={<Inbox />} text="Aucune facture fournisseur synchronisée." />}</div>}</main>;
}
function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex flex-col items-center gap-2 p-10 text-sm text-zinc-500">{icon}{text}</div>; }
